### ISSUE TITLE
Purchase object is probably redundant

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#221]
Probably `Purchase` business object and `Purchase` db table are redundant. Because the info that these Purchase objects store can as well be stored in the `Transaction` object (with slight changes to this object) or are already stored there. 

So probably we should get rid of 'Purchase'.

Hadn't had the time yet to have a deeper look, though. One challenge might be that not all the transactions are purchases (some are credit from social accounting, others are transfers of wages).

**Comment by seppeljordan** [comment]
Issue is obsolete. The `Purchase` class might still be useful.
