### ISSUE TITLE
``flask run`` does raise an error 

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#324]
After merge of PR #307, when I try to run ``flask run`` in bash, it raises the following error:

```
flask.cli.NoAppException: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
```

I did adapt the environment variable ``ARBEITSZEIT_APP_CONFIGURATION`` as stated in the Readme.

**Comment by mi01** [comment]
I can confirm this error. Running `export FLASK_APP=arbeitszeit_flask` in the bash solved this problem temporary, but adding the same environment variable to `.flaskenv` or `.env` does not work.

**Comment by seppeljordan** [comment]
The issue does not occur with my setup.

Here is my environment:

```
export ARBEITSZEIT_APP_CONFIGURATION=$PWD/arbeitszeit_flask/development_settings.py
export DEV_SECRET_KEY=...
export DEV_DATABASE_URI=postgresql:///arbeitszeit_develop
export FLASK_APP=arbeitszeit_flask
export FLASK_ENV=development
```

**Comment by sloschert** [comment]
Ah, thanks, now I found the reason for my error:
I had the wrong file name:
```$PWD/arbeitszeit_flask/development-settings.py```

(with a dash instead of underscore)
I think I made the mistake because the file had a dash before - you as well, @mi01 ?

**Comment by mi01** [comment]
> Ah, thanks, now I found the reason for my error: I had the wrong file name: `$PWD/arbeitszeit_flask/development-settings.py`
> 
> (with a dash instead of underscore) I think I made the mistake because the file had a dash before - you as well, @mi01 ?

I had the correct path, but i had to set FLASK_APP as i said (which was not set before). Settings this environment variable also seems to work with an `.env` file now.

**Comment by seppeljordan** [comment]
@sloschert Is the issue resolved for you as the OP of the issue?

**Comment by sloschert** [comment]
I guess we should add an explanation to the Readme file (under "Caveats") that developers should add an environment variable ``export FLASK_APP=arbeitszeit_flask``.

Then we can close this issue.
