### ISSUE TITLE
Certificates are transferred multiple times when when user uses "Back" navigation in browser

### ISSUE THREAD

**Issue by seppeljordan** [arbeitszeit/arbeitszeitapp#326]
What was observed:

I transferred some certificates via the "Bezahlen Produktionsmittel" form. After doing so successfully I clicked the "Back" button in my browser (firefox). Afterwards I checked my accounts and noticed that the last payment had been made 3 times in one minute in addition to the original (intended) payment.

What I expected:

I expected the browser navigation to not resubmit the payment form to the server.

**Comment by knit-bee** [comment]
[This](https://stackoverflow.com/questions/62704869/python-flask-stop-page-from-re-submitting-a-post-request) seems to describe the same problem.

**Comment by sloschert** [comment]
Yes, and there: https://stackoverflow.com/questions/28184154/why-will-wtforms-submit-again-when-i-refresh-the-page

**Comment by sloschert** [comment]
Btw, my chromium browser shows a warning when clicking the "Back" button: 

```
Erneute Formular-Übermittlung bestätigen
Damit diese Webseite richtig angezeigt wird, werden die Daten benötigt, die Sie vorher eingegeben haben. Sie können diese Daten noch einmal senden, dabei werden jedoch sämtliche Aktionen wiederholt, die vorher durch diese Seite ausgeführt wurden.
Klicken Sie auf die Schaltfläche zum erneuten Laden, um die für das Laden der Seite erforderlichen Daten noch einmal zu senden.
ERR_CACHE_MISS
```
