### ISSUE TITLE
Designing user story for managing plan drafts

### ISSUE THREAD

**Issue by seppeljordan** [arbeitszeit/arbeitszeitapp#398]
Right now it is unwieldy to manage plan drafts. These drafts cannot be deleted nor edited. We need to think about a proper user interface managing drafts.

Do we need a plan draft system at all?
Should a plan draft disappear when the user files it to social accounting?
Should we allow plan draft creation from an already existing plan?
Should plan drafts appear in the plan overview `/company/my_plans`?

**Comment by sloschert** [comment]
Closing outdated issue.
