### ISSUE TITLE
Improve input labels and help text on plan creation page

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#412]
**Description**

The create plan draft page (`/company/create_draft`) should be more user friendly by explaining what fixed and liquid means of production are  and which units are requested in the user input fields

**Details:**

As remarked by several users in our workshop the following things should be improved on the  view:

- [x] Explain what fixed and liquid means of production are. This information could be given in the "help modal" (the blue circle with a question mark in it) with the id `id_costs`.
![Bildschirmfoto vom 2024-02-05 21-38-19](https://github.com/arbeitszeit/arbeitszeitapp/assets/61537351/d353b894-9f29-480d-b092-aa6923160ae6)

- [x] Make it explicit that users should specify the following input fields in hours: "Costs for fixed means of production", "Costs for liquid means of production", "Costs for labour". This could be done for example by adding "hours" in parenthesis ("Costs for fixed means of production (hours)", "Costs for liquid means of production (hours)", "Costs for labour (hours)".)

**Comment by petsch0** [comment]
second task was done in #973

**Comment by petsch0** [comment]
first task done in #975
