### ISSUE TITLE
Create show_member_purchases-Presenter

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#432]
Currently, the list of past purchases of a member gets shown correctly, but the backend is messy: In the Member-route `member/kaeufe` (endpoint: `arbeitszeit_flask/member/routes.py` -> `my_purchases()`), there is no presenter. The list of past purchases are passed from the Use Case directly into the html template. 

As a first step towards proper refactoring, we need a presenter that takes the Use Case response (`PurchaseQueryResponse`) as a single argument and gives back a View Model. 

- This View Model should only consist out of basic data types, ideally only strings and bools. 
- The presenter should be tested.
- The `purchase_date` should be formatted in the presenter.
- The `purpose` should be made translatable in the presenter.
- `price_per_unit` and `price_total` should be rounded in the presenter.

We can take existing presenters in `arbeitszeit_web/presenters` as models.

*Edit*
Because, in the meantime since 3b554adbd939d1910766dd1a979a14c5bcc5717e, there is a Presenter for the Member-route `member/kaeufe` (endpoint: `arbeitszeit_flask/member/routes.py` -> `my_purchases()`) (`MemberPurchasesPresenter` in `member_purchases.py`) the new presenter will be used for the company route (route `/company/purchases`, endpoint: `arbeitszeit_flask/company/routes.py` -> `my_purchases()`).

**Comment by philipbroistedt** [comment]
Translation:
All Texts in `my_purchases.html` are already translated. The presenter has no strings. There is nothing left to translate.

**Comment by sloschert** [comment]
Yes, I think this issue can be actually closed, or what do you think? The `price_total` property in the presenter could still be rounded, but that's not super important.

**Comment by philipbroistedt** [comment]
After changing to a company presenter (see edit in issue description), the branch is finally merged and this issue can be closed.
