### ISSUE TITLE
RFC: Plan approval process

### ISSUE THREAD

**Issue by seppeljordan** [arbeitszeit/arbeitszeitapp#452]
# The Problem

Currently the application does not support a proper approval process
for plans. Instead the current approach is more "self service"
oriented where companies can basically approved their own plans.

We want to implement proper planning control via public
accounting. Also we would like to maintain the ability to auto-approve
plans in certain situations, e.g. educational instances of the app.

# A proposal for a solution

The `SeekApproval` use case how it is used currently should actually
be understood as a separate use case that is different from the
regular use case of filing a plan with public accounting. From here on
out I willl call this separate use case `AutoApprovePlan`.

Currently the approval process calls two different use cases in one
view/route: `SeekApproval` and `ActivatePlanAndGrantCredit`. We should
refactor our code so that those two use cases are merged into a single
use case (`AutoApprovePlan`).

Then we start developing a new and separate use case called
`FilePlanWithPublicAcocunting` which implements the business logic of
the "traditional" process for plan. This will allow us to develop the
approval process without breaking the current workflow.

Before the production release of the app we introduce a [feature
toggle](https://en.wikipedia.org/wiki/Feature_toggle) that allows app
administrators to enable or disable the `AutoApprovePlan` workflow.

This will allow us to have the educational instance and the productive
instance of the app with different plan approval workflows without
implementing a complicated plug-in system.

**Comment by sloschert** [comment]
I agree.

**Comment by sloschert** [comment]
Closing this issue being outdated.
