### ISSUE TITLE
Module tests do not run on Windows

### ISSUE THREAD

**Issue by philipbroistedt** [arbeitszeit/arbeitszeitapp#495]
**(1) Error with year '1'**
In file _show_my_plans.py_:
```
def __format_date(self, date: Optional[datetime]) -> str:
      return f"{date.strftime('%d.%m.%y')}" if date else "-"
      ValueError: format %y requires year >= 1900 on Windows
```
Called with Pythons  datetime.MINYEAR == 1 (generated by _datetime.min_) in _test_show_my_plans_presenter.py_ , Line 52 and 61

```
 plan = self.plan_generator.create_plan(activation_date=datetime.min)
```

**(2) 2nd error: AssertionError**
```
E       AssertionError: assert <TransactionTypes.payment_of_liquid_means: 7> == <TransactionTypes.sale_of_fixed_means: 1
1>
E        +  where <TransactionTypes.payment_of_liquid_means: 7> = TransactionInfo(transaction_type=<TransactionTypes.pay
ment_of_liquid_means: 7>, date=datetime.datetime(2022, 8, 24, 20, 59, 35, 422251), transaction_volume=Decimal('-10'), ac
count_type=<AccountTypes.r: 'r'>, purpose='test purpose').transaction_type
E        +  and   <TransactionTypes.sale_of_fixed_means: 11> = TransactionTypes.sale_of_fixed_means

tests\use_cases\test_get_company_transactions.py:203: AssertionError
```

There are several assert errors. They all result from a wrong/ not expected order of transactions.
These action have been created with the `TransactionGenerator` and sorted with `GetCompanyTransactions`. The `TransactionGenerator` uses the creation `time now_minus_one_day()` for all new transactions. 

The problem is an isufficient time resolution of the `now()` Function on Windows machines. So, all transactions have the same timestamp (sometimes it is different) and the sort function cannot sort them in the intended order. So the checks fail...

See
https://stackoverflow.com/questions/31352912/python-resolution-of-datetime-now
https://stackoverflow.com/questions/3729169/how-can-i-get-the-windows-system-time-with-millisecond-resolution

**Comment by philipbroistedt** [comment]
**Quick fix for 1st error**
```
    def __format_date(self, date: Optional[datetime]) -> str:
        try:
            datestr = f"{date.strftime('%d.%m.%y')}" if date else "–"
        except:
            datestr = "-"
        return datestr
```

**Comment by sloschert** [comment]
Thanks for raising this!
1st error: This seems to be a Windows specific issue. We are actually not planning to support Windows in development or production. We can discuss this as anything else in our Wednesday meetings, though.
2nd error: Unfortunately I cannot reproduce this error.

**Comment by philipbroistedt** [comment]
> **Quick fix for 1st error**
> 
> ```
>     def __format_date(self, date: Optional[datetime]) -> str:
>         try:
>             datestr = f"{date.strftime('%d.%m.%y')}" if date else "–"
>         except:
>             datestr = "-"
>         return datestr
> ```
> 
> Normally, no date before 1900 should occure in the system. Therefor the test (two occurrenes in 'test_show_my_plans_presenter.py') chould als be corrected (e.g. datetime.min --> datetime.now())
> 
> Nevertheless: A correct error handling is always a good idea!

**Comment by philipbroistedt** [comment]
PR #528 merged.
All tests run on windows. Currently.
