### ISSUE TITLE
Wrong order of user inputs in plan creation (front-end)

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#626]
**Problem:**
When a company creates a plan, i gets first asked, what the costs for its entire product will be, and after that, what unit and amount it produces. 
This order is counterintuitive IMO.

![image](https://user-images.githubusercontent.com/61537351/213908452-4438b87c-c446-4b7f-9af9-9a0e075d5b6c.png)

**Proposed solution:** 
The order of the two blocks should be flipped: "Smalles delivery unit" and "Amount" first, Costs for means of production and labour after that.

**Comment by lukaszcalka** [comment]
Hey, I've seen your project somewhere on reddit and wanted to help out. I've swapped those two blocks but I'm getting 403 when trying to push the branch and open a PR.
