### ISSUE TITLE
Bestätigung von Arbeiter*innen beim Hinzufügen zu Betrieben

### ISSUE THREAD

**Issue by seppeljordan** [arbeitszeit/arbeitszeitapp#67]
Momentan können Arbeiter*innen keinen Einfluss darauf nehmen, ob Betriebe sie als Arbeitskräfte hinzu fügen.  Dass sollte sich ändern. Möglich wäre, so eine Art "Inbox" für Arbeitskräfte, wo durch einen Klick auf eine Bestätigungsnachricht die Beschäftigung in einem Betrieb bestätigt oder abgelehnt werden kann.

**Comment by sloschert** [comment]
@seppeljordan can we close this?

**Comment by seppeljordan** [comment]
The feature is implemented as described in the OP.
