### ISSUE TITLE
RFC: Process for changing user email addresses

### ISSUE THREAD

**Issue by seppeljordan** [arbeitszeit/arbeitszeitapp#702]
/cc @philipbroistedt @sloschert @Amittai-Aviram 
I would like to propose a process which for letting user change their email address. Please let me know what you think about this proposal in the comments below.

1. Users should be able to request that their email address should be changed via the web interface. When requesting this change the user must provide the new email address in a web form. The system will reject the request if the email is already in use by any other account. 
2. If accepted then the user will receive an email with a confirmation link to their new email address. At the same time the system will send an email to the old email address, warning the user that the process to change their email address in the arbeitszeitapp was initiated. This email should contain an email address that lets the user contact an admin in case someone else is messing with their account. 
3. The confirmation link should lead to a page where the user can confirm the change. The user must provide their password for authentication purposes in this form. 
4. After the change was confirmed the system will use the new email address and "forget" about the old email address.

In case a user has more than 1 account type associated with their email address, the process must affect all those accounts. Disassociating an account from an existing email address should be a separate process and is not the subject of this proposal.

**Comment by seppeljordan** [comment]
This addresses the feature request from #372

**Comment by Amittai-Aviram** [comment]
This looks good to me.  Is there any protection against a DoS attack?  I guess that question extends to the app more generally.

In solidarity,
Amittai

Amittai Aviram
646-483-2639
***@***.***
http://www.amittai.com
