### ISSUE TITLE
Starting app in pip environment fails

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#704]
Starting app in pip environment fails, with flask_profiler raising a `sqlite3.OperationalError`.

Steps to reproduce:
- Deactivate nix environment
- Install dependencies into environment with `pip install -r requirements-dev.txt`
- Run `python -m flask run -h localhost`
- visit http://localhost:5000/

**Comment by seppeljordan** [comment]
Could you please provide the output of the failed attempt?

**Comment by seppeljordan** [comment]
Could you try `pip install -U -r requirements-dev.txt` once again before retrying?

**Comment by seppeljordan** [comment]
Deleting `flask_profiler.sql` should resolve the issue.
