### ISSUE TITLE
Flask constantly restarting development server

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#705]
As I noticed today, flask is constantly reloading the development server after running `python -m flask run -h localhost`.

The following ouput is generated in the terminal:
"detecting change in [file]"
"restarting with watchdog (inotify)"

This behaviour makes it impossible to use breakpoints and the python debugger.

Happens with pip and nix environment, tested on two different ubuntu computers.

**Comment by seppeljordan** [comment]
I guess that you are trying to utilize the breakpoint feature from your IDE/text editor?

Try `python -m flask run --no-reload`.

**Comment by seppeljordan** [comment]
I am experiencing the same issue. I guess that this is a bug with flask and not with the arbeitszeitapp.

**Comment by seppeljordan** [comment]
My guess is that we are experiencing this bug: https://github.com/pallets/werkzeug/issues/2603
