### ISSUE TITLE
Language toggle not working on Mac

### ISSUE THREAD

**Issue by petsch0** [arbeitszeit/arbeitszeitapp#956]
Tested on Apple M1 Pro, macOS Sonoma 14.3.1 on Firefox, Chrome, and Safari. 

When clicking on the "Deutsch"-Button to switch to German, it seems like the page is reloading, but nothing changes. Also same behavior on http://app.arbeitszeitrechnung.org/.

@Amittai-Aviram @rhklee can you confirm this?

**Comment by petsch0** [comment]
> Is there any output from the dev server when you try to switch languages in your local dev environment?

`127.0.0.1 - - [16/Feb/2024 12:25:16] "GET / HTTP/1.1" 200 -`
`127.0.0.1 - - [16/Feb/2024 12:25:16] "GET /static/main.css HTTP/1.1" 200 -`
`127.0.0.1 - - [16/Feb/2024 12:25:16] "GET /static/bulma.css HTTP/1.1" 200 -`
`127.0.0.1 - - [16/Feb/2024 12:25:16] "GET /static/main.js HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 12:25:16] "GET /favicon.ico HTTP/1.1" 404 -`
`127.0.0.1 - - [16/Feb/2024 12:25:19] "GET /language=de HTTP/1.1" 302 -`
`127.0.0.1 - - [16/Feb/2024 12:25:19] "GET / HTTP/1.1" 200 -`
`127.0.0.1 - - [16/Feb/2024 12:25:19] "GET /static/main.js HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 12:25:19] "GET /static/main.css HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 12:25:19] "GET /static/bulma.css HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 12:25:22] "GET /language=en HTTP/1.1" 302 -`
`127.0.0.1 - - [16/Feb/2024 12:25:22] "GET / HTTP/1.1" 200 -`
`127.0.0.1 - - [16/Feb/2024 12:25:22] "GET /static/bulma.css HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 12:25:22] "GET /static/main.css HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 12:25:22] "GET /static/main.js HTTP/1.1" 304 -`



> I am pretty sure that the issue with app.arbeitszeitrechnung.org comes from session cookies not working properly after an update. Maybe the cookie expired in the meantime or you acquired a new cookie by some other means (e.g. login)?

yes, that's possible. I think it worked after I logged in.

**Comment by petsch0** [comment]
so I did a little printf debugging and there is nothing wrong with the code. 
`[2024-02-16 18:24:31,473] INFO in routes: session: <SecureCookieSession {'_fresh': True, '_id': '3fdea7fb873a6d707156d5a81ea581557434a6d07b36cc8fe2f4e071b8b635eeb8f516ad0f6b066d656d635fa422c9e2f0e57eaf443f47bacf3d74a2711a20fb', '_user_id': '076702bc-6626-4ccb-bfe9-eefe4b4bed25', 'csrf_token': '02f0dacaa3cb9847eca1b9a5bf5b563fe8cf73c3', 'language': 'de', 'user_type': 'company'}>`
`127.0.0.1 - - [16/Feb/2024 18:24:31] "GET /language=de HTTP/1.1" 302 -`
`[2024-02-16 18:24:31,506] INFO in babel: get locale`
`[2024-02-16 18:24:31,506] INFO in babel: session lang = de`
`127.0.0.1 - - [16/Feb/2024 18:24:31] "GET /company/dashboard HTTP/1.1" 200 -`
`127.0.0.1 - - [16/Feb/2024 18:24:31] "GET /static/bulma.css HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 18:24:31] "GET /static/main.css HTTP/1.1" 304 -`
`127.0.0.1 - - [16/Feb/2024 18:24:31] "GET /static/main.js HTTP/1.1" 304 -`
maybe the issue comes from a different babel version that is used with darwin aarch64 platform?

**Comment by rhklee** [comment]
On https://app.arbeitszeitrechnung.org/ and the demo-app sites the change language toggle worked for me as an anonymous user without issues.

**Comment by petsch0** [comment]
toggle works fine, just did not run translation
